### ISSUE TITLE
Memory usage is too high

### ISSUE THREAD

**Issue by jimbobbennett** [adafruit/Adafruit_CircuitPython_AzureIoT#13]
This library uses a LOT of memory. Just importing the library uses 91,872 bytes 😲

I'm slowly working through it trying to reduce this.

I've raised #12 to change from depending on [CircuitPython_HMAC](https://github.com/jimbobbennett/CircuitPython_HMAC) and Adafruit_CircuitPython_Hashlib, to instead having just the bits needed and that saves 18,640 bytes.

As I make more memory reductions I'll add them here and link the PRs.

We could also save about ~6,000 bytes by splitting this into two libraries - one for IoT Hub and one for IoT Central. It's *very* unlikely someone will want to connect to both from the same project. @brentru - what do you think about this?

**Comment by jimbobbennett** [comment]
Removed dependencies on base64 and Parse, just pulling in the code that is needed. Now saved 37K.

Seems the biggest library is miniMQTT at 20K. Not sure what can be removed from this.

**Comment by tannewt** [comment]
> We could also save about ~6,000 bytes by splitting this into two libraries - one for IoT Hub and one for IoT Central. It's _very_ unlikely someone will want to connect to both from the same project. @brentru - what do you think about this?

This is a technique I like generally. Have lots of small libraries for specific jobs. I cover it in the design guide which is probably not well known enough: https://circuitpython.readthedocs.io/en/5.0.x/docs/design_guide.html#lots-of-small-modules

**Comment by jimbobbennett** [comment]
@tannewt - is there a way to create multiple libraries from a single repo? Or would there need to be multiple repos?

**Comment by tannewt** [comment]
Libraries was the wrong term. I should have said "modules" meaning .py files. Each .py file is loaded separately. It's ok that a library (== repo) has multiple .py files.

**Comment by brentru** [comment]
@jimbobbennett  This seems to have been resolved in #12. Closing...
