### ISSUE TITLE
Import Error: no module named 'adafruit minimqtt.MQTT'

### ISSUE THREAD

**Issue by Peter-McKinney** [adafruit/Adafruit_CircuitPython_AzureIoT#22]
The import adafruit_azuireiot statement throws an error from the 6.x adafruit library bundle.

`from adafruit_azureiot import IoTHubDevice` 

It looks like MiniMQTT is already aware of this issue but this issue was never opened on this repository. 

[MiniMQTT Issue 51](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/51)
[Link to referenced comment](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/51#issuecomment-729772968)

I believe this is the import that is affected in the iot_mqtt.py. [iot_mqtt.py](https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/blob/2a83561e0585e201fae2316c7d5d4f1806512ac0/adafruit_azureiot/iot_mqtt.py#L35)

Please let me know if you need further information.

**Comment by askpatrickw** [comment]
There are several things needed for CP6 support see Issue  #21  for more info as well.

**Comment by brentru** [comment]
@Peter-McKinney  The last thing on the list @askpatrickw  linked above is a large update to MiniMQT.  I'm currently blocking on a socket API issue https://github.com/adafruit/circuitpython/issues/3836 and will continue with MiniMQTT development once it's resolved. 

I'll take a look back at this issue once I release the next major version of MMQTT since it's required for this library to work properly with CP6.

**Comment by askpatrickw** [comment]
Actually, now I can see where the current time is being used. @jimbobbennett  please correct if I'm wrong.

> To use this library, you will need to create an ESP32_SPI WifiManager, connected to WiFi. You will also need to set the current time, as this is used to generate time-based authentication keys. One way to do this is via the Adafruit CircuitPython NTP library ..

https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/blob/master/adafruit_azureiot/iotcentral_device.py#L130
uses is to set the token_expiry `token_expiry = int(time.time() + self._token_expires)`

So the library doesn't _need_ NTP but all the examples use it.

**Comment by brentru** [comment]
This has been resolved by https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/pull/23 and has been merged into `master`.
