### ISSUE TITLE
id_scope not found

### ISSUE THREAD

**Issue by nagkumar91** [adafruit/Adafruit_CircuitPython_AzureIoT#32]
Hey,
I was following the readme and the documentation here - https://learn.adafruit.com/using-microsoft-azure-iot-with-circuitpython/azure-iot-central-setup and it looks like the device creation part in Azure IOT has changed. Here's how it looks like now:
<img width="1306" alt="Screen Shot 2021-08-19 at 3 12 06 PM" src="https://user-images.githubusercontent.com/4727422/130151159-5aaa56ce-6ef9-40da-9645-a57d2e03dfed.png">
I'm not able to find the `id_scope` which is mandatory when I try to initialize my device using `IoTCentralDevice`.
Any help would be appreciated.

**Comment by askpatrickw** [comment]
The id scope is in the admin pages for your iot central application.
