### ISSUE TITLE
May need update due to `adafruit_logging` 4.0.0

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_AzureIoT#48]
This library likely needs updates due to the `adafruit_logging` library upgrade.  New use should be CPython compatible, and it may be worth allowing the CPython `logging` module to be imported if available.

Some common issues that are now present across libraries:

- Locations of classes have changed, and some may have been removed.
- `PrintLogger` no longer exists; instead, instance a `Logger` and add a `StreamHandler` instance with default arguments as the handler.

**Comment by ladyada** [comment]
@BlitzCityDIY did mention it still works - but if something got missed she can help test PRs!
