### ISSUE TITLE
Can't use this module on PyPortal or Metro M4 Airlift Lite due to no SSL module

### ISSUE THREAD

**Issue by MathCatsAnd** [adafruit/Adafruit_CircuitPython_AzureIoT#55]
Disclosure: I'm completely new to adafruit and doing my very first project.

I am unable to use the `adafruit_azureiot` module on my PyPortal or my Metro M4 Airlift Lite. Both of these boards use `adafruit_esp32spi` and have no `wifi` or `ssl` module in their CircuitPython installations. There was an update to this `adafruit_azureiot` module which added an import of `ssl` in the `iot_mqtt.py` file.

https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/commit/75af72b6b80388f2365c736039deb8507b11451d

As such, without building a custom CircuitPython installer for these boards, I am unable to use `adafruit_azureiot` since just importing a function will will trigger `ModuleNotFoundError` when `iot_mqtt.py` tries to import `ssl`.

**Comment by tekktrik** [comment]
I'm not entirely familiar with this library, but you should be able to overcome the `wifi` module by using `adafruit_esp32spi` and modifying the code accordingly.  The `ssl` issue however doesn't have a similar fix.

Let me see if I'm missing something.

**Comment by MathCatsAnd** [comment]
Yes, indeed, I am using the `adafruit_esp32spi` module to connect to wifi, no problems there. I just mentioned it since I usually see the two modules together (either a board has `wifi` and `ssl` or it has neither). The board describe having "onboard TLS/SSL."

> Espressif ESP32 Wi-Fi coprocessor with TLS/SSL support built-in

So my naive understanding is that `esp32spi` should in some way replace the *pair* of `wifi` and `ssl`, though it is only the `ssl` part causing a problem for me here. (I naively created an empty `ssl.py` file to get past the import, but sadly there is a call to it when trying to register a device.

**Comment by MathCatsAnd** [comment]
Would it make sense to add to the documentation on this (or did I just not see it)? I know the library documentation says that CircuitPython (implicitly in its entirety) is a requirement which technically covers it. However, for me as a newbie, it was a learning experience to find out all these boards "with CircuitPython" often only have a subset of it.

So does it make sense to clarify the builtins needed within the documentation to assist in figuring out board compatibility? I had purchased a PyPortal since it appeared compatible based on a [tutorial](https://learn.adafruit.com/using-microsoft-azure-iot-with-circuitpython/azure-iot-central-setup). However, the tutorial was written before the mentioned commit. I tried rolling back the library to before the commit, but instead encountered a socket error. I will try to keeping rolling things back to see if I can reach a compatible version. (Meanwhile, I ordered a different board and left feedback on the aforementioned tutorial.) Thanks!

**Comment by tekktrik** [comment]
Submitted feedback to the Learn Guide about this so it can be addressed.  I do think adding information about compatibility would be helpful as well, if you're up for submitting a PR, let me know - otherwise I can submit one.

**Comment by MathCatsAnd** [comment]
Very happy to make an attempt! I will try to do that now.

**Comment by MathCatsAnd** [comment]
Done. I will make an attempt to understand how this works and see if I can edit the library, but as I am so new to board-level work I have no idea how long that would take me...in case anyone sees this and wants to work on the issue.

**Comment by tekktrik** [comment]
I'll take a look at the not shortly, but in the meantime, if you do want to do this tutorial, you could try to use [the firmware](https://github.com/adafruit/circuitpython/releases/tag/5.3.0) and [the libraries](https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/tag/20200526) from around May 26, 202 if you haven't already tried, at least while this is still an issue.
